[testServer]
BROKER_HOST = 100.114.28.75
BROKER_PORT = 5672
USER = admin1
PASSWORD = teamcyber490
VHOST = testHost
EXCHANGE = authServerExchange
QUEUE = authServer
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
