[statusServer]
BROKER_HOST = 100.78.109.70
BROKER_PORT = 5672
USER = admin2
PASSWORD = TeamCyber490
VHOST = testHost
EXCHANGE = deployExchange
QUEUE = statusQueue
ROUTING_KEY = statusQueue
EXCHANGE_TYPE = direct
AUTO_DELETE = false

; --- 2. DEV ENVIRONMENT ---
[dev_web]
BROKER_HOST = 100.78.109.70
BROKER_PORT = 5672
USER = admin2
PASSWORD = TeamCyber490
VHOST = testHost
EXCHANGE = deployExchange
QUEUE = q_dev_web
ROUTING_KEY = q_dev_web
EXCHANGE_TYPE = direct
AUTO_DELETE = false

[dev_db]
BROKER_HOST = 100.78.109.70
BROKER_PORT = 5672
USER = admin2
PASSWORD = TeamCyber490
VHOST = testHost
EXCHANGE = deployExchange
QUEUE = q_dev_db
ROUTING_KEY = q_dev_db
EXCHANGE_TYPE = direct
AUTO_DELETE = false

[dev_dmz]
BROKER_HOST = 100.78.109.70
BROKER_PORT = 5672
USER = admin2
PASSWORD = TeamCyber490
VHOST = testHost
EXCHANGE = deployExchange
QUEUE = q_dev_dmz
ROUTING_KEY = q_dev_dmz
EXCHANGE_TYPE = direct
AUTO_DELETE = false

; --- 3. QA ENVIRONMENT ---
[qa_web]
BROKER_HOST = 100.78.109.70
BROKER_PORT = 5672
USER = admin2
PASSWORD = TeamCyber490
VHOST = testHost
EXCHANGE = deployExchange
QUEUE = q_qa_web
ROUTING_KEY = q_qa_web
EXCHANGE_TYPE = direct
AUTO_DELETE = false

[qa_db]
BROKER_HOST = 100.78.109.70
BROKER_PORT = 5672
USER = admin2
PASSWORD = TeamCyber490
VHOST = testHost
EXCHANGE = deployExchange
QUEUE = q_qa_db
ROUTING_KEY = q_qa_db
EXCHANGE_TYPE = direct
AUTO_DELETE = false

[qa_dmz]
BROKER_HOST = 100.78.109.70
BROKER_PORT = 5672
USER = admin2
PASSWORD = TeamCyber490
VHOST = testHost
EXCHANGE = deployExchange
QUEUE = q_qa_dmz
ROUTING_KEY = q_qa_dmz
EXCHANGE_TYPE = direct
AUTO_DELETE = false

; --- 4. PROD ENVIRONMENT ---
[prod_web]
BROKER_HOST = 100.78.109.70
BROKER_PORT = 5672
USER = admin2
PASSWORD = TeamCyber490
VHOST = testHost
EXCHANGE = deployExchange
QUEUE = q_prod_web
ROUTING_KEY = q_prod_web
EXCHANGE_TYPE = direct
AUTO_DELETE = false

[prod_db]
BROKER_HOST = 100.78.109.70
BROKER_PORT = 5672
USER = admin2
PASSWORD = TeamCyber490
VHOST = testHost
EXCHANGE = deployExchange
QUEUE = q_prod_db
ROUTING_KEY = q_prod_db
EXCHANGE_TYPE = direct
AUTO_DELETE = false

[prod_dmz]
BROKER_HOST = 100.78.109.70
BROKER_PORT = 5672
USER = admin2
PASSWORD = TeamCyber490
VHOST = testHost
EXCHANGE = deployExchange
QUEUE = q_prod_dmz
ROUTING_KEY = q_prod_dmz
EXCHANGE_TYPE = direct
AUTO_DELETE = false
